//@version=5
strategy("MACD Strategy", shorttitle="MACD", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

//@strategy_description=This script implements a MACD strategy for long positions in stocks. It uses MACD, signal line, and SMA to determine entry and exit points for long positions.
//@tags=macd, ema, sma, strategy, trading, stocks

// Input parameters
fastLength = input(50, "Fast Length")
slowLength = input(75, "Slow Length")
macdLength = input(35, "MACD Length")
var int smaLength = input(250, "SMA Length")

// Calculate MACD components
float fastEMA = ta.ema(close, fastLength)
float slowEMA = ta.ema(close, slowLength)
float macdLine = fastEMA - slowEMA
float signalLine = ta.ema(macdLine, macdLength)
float histogram = macdLine - signalLine

// Calculate SMA
float sma = ta.sma(close, smaLength)

// Entry and exit conditions
bool longCondition = histogram > 0 and close > sma
bool exitCondition = close < sma

// Strategy execution
if (longCondition)
    strategy.entry("Long", strategy.long)

if (exitCondition)
    strategy.close("Long")

// Plotting
plot(histogram, title="MACD Histogram", style=plot.style_histogram, color=color.new(color.black, 0))
plot(macdLine, title="MACD Line", color=color.new(color.blue, 0))
plot(signalLine, title="Signal Line", color=color.new(color.orange, 0))
plot(sma, title="SMA", color=color.new(color.red, 0))
