// Copyright (c) GreenScale. All rights reserved.
// Description: Based on https://www.investopedia.com/articles/trading/08/turtle-trading.asp
// @version=5
strategy("Stocks | Long | Turtle Strategy | Daily", overlay=true)

// Checking if the current high is greater than the highest high of the previous 40 periods
checkB = high > ta.highest(high[1], 40)

// Checking if the current low is lower than the lowest low of the previous 20 periods
checkS = low < ta.lowest(low[1], 20)

// Entering a long position if checkB condition is true
if (checkB)
    strategy.entry("Long", strategy.long)

// Calculating the Average True Range (ATR) with a period of 14
atrc = ta.atr(14)

// Tracking the ATR Stop loss
var float entry_atr = na
var float atr_close = na

// If the previous atr_close is not available, set entry_atr to na. Otherwise, calculate the new value based on the position size comparison
if (na(atr_close[1]))
    entry_atr := na
else
    entry_atr := strategy.position_size > strategy.position_size[1] ? atrc : entry_atr[1]

// Plotting the ATR-based stop loss level
plot(strategy.position_avg_price - (2 * entry_atr))

// Closing the position if checkS condition is true or if the close price is lower than the ATR-based stop loss level
if (checkS or close < strategy.position_avg_price - (2 * entry_atr))
    strategy.close("Long")
