// Copyright (c) GreenScale. All rights reserved.
// Description: Based on https://www.investopedia.com/terms/p/pullback.asp
// @version=5
strategy("Pullback Trading Strategy | Long", shorttitle="Pullback", overlay=true)

// Input parameters
SL = input(0.10, title="Stop Loss %")
TP = input(0.30, title="Take Profit %")

if close > ta.sma(close, 200) and close < ta.sma(close, 50)
    strategy.entry("long", strategy.long)

// Calculating the exit price for stop loss (sl) and take profit (tp)
longstop = strategy.position_avg_price * (1 - SL)
longprofit = strategy.position_avg_price * (1 + TP)

// For long positions
if strategy.position_size > 0
    strategy.exit(id = "close", stop = longstop, limit = longprofit)
