// Copyright (c) GreenScale. All rights reserved.
// Description: Based on https://www.investopedia.com/terms/a/adx.asp
// @version=5
strategy("Stocks | Long | ADX Strategy | Daily", overlay=true)

// Setting the number of days for calculations
days = input.int(title="days", defval=30)

// Setting the period for the simple moving average (SMA)
smap = input.int(title="ma period", defval=200)

// Calculating the SMA based on the closing prices over the specified period
smaval = ta.sma(close, smap)

// Calculating the Directional Movement Index (DMI) with a period of 5 and smoothing period of 5
[diplus, diminus, adx] = ta.dmi(5, 5)

// Checking if the current closing price is higher than the closing price 'days' bars ago,
// the ADX value is greater than 50, and the current closing price is higher than the calculated SMA
if close > close[days] and adx > 50 and close > smaval
    strategy.entry("Long", strategy.long)

// Checking if the current closing price is lower than the calculated SMA
if close < smaval
    strategy.close("Long")
