// Copyright (c) GreenScale. All rights reserved.
// Description: Based on https://www.investopedia.com/terms/m/macd.asp
// @version=5
strategy("Daily | Long | MACD Strategy", shorttitle="MACD Strategy", overlay=true)

// Input parameters that can be optimized
fastl = input(33, "Fast Length")
slowl = input(75, "Slow Length")
macdl = input(35, "MACD Length")

// Calculate MACD line using exponential moving averages
MACD = ta.ema(close, fastl) - ta.ema(close, slowl)

// Calculate signal line using exponential moving average of MACD line
signal = ta.ema(MACD, macdl)

// Calculate histogram by subtracting signal line from MACD line
hist = MACD - signal

// Entry condition: if histogram is positive and close price is above 250-period simple moving average
if hist > 0 and close > ta.sma(close, 250)
    strategy.entry("Long", strategy.long)

// Exit condition: if close price is below 250-period simple moving average
if close < ta.sma(close, 250)
    strategy.close("Long")

// Plot histogram
plot(hist, title="MACD_hist", style=plot.style_histogram, color=color.black)

// Plot MACD line
plot(MACD, title="MACD_line", color=color.blue)

// Plot signal line
plot(signal, title="signal_line", color=color.orange)
