//@version=5
strategy("Average Directional Index Strategy", shorttitle="ADX", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

//@description=This script implements an ADX (Average Directional Index) strategy for stocks. It uses ADX, SMA, and price comparisons to determine entry and exit points for long positions.
//@tags=adx, sma, strategy, trading, stocks

// Input settings
var int DAYS = input.int(title="Number of Days", defval=30)
var int SMA_PERIOD = input.int(title="MA Period", defval=200)

// Calculating indicators
sma_value = ta.sma(close, SMA_PERIOD)
[diplus, diminus, adx] = ta.dmi(5, 5)

// Entry and exit conditions
long_condition = close > close[DAYS] and adx > 50 and close > sma_value
exit_condition = close < sma_value

// Entry and exit conditions & Strategy execution
if (long_condition)
    strategy.entry("Long", strategy.long)

if (exit_condition)
    strategy.close("Long")

// Plotting
plot(sma_value, title="SMA", color=color.blue)
plot(adx, title="ADX", color=color.red)
