//@version=5
strategy("Inside Days Strategy", shorttitle="Inside Days", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

//@description=This script implements an Inside Day strategy for long positions in stocks. It identifies inside day patterns and uses RSI for exit conditions. The strategy enters a long position when an inside day is detected and exits based on an RSI threshold.
//@tags=inside-day, rsi, strategy, trading, stocks

// Defining the inside day
// The inside day is defined as a condition where the previous day's high is greater than the current day's high
// and the previous day's low is lower than the current day's low.
id = high[1] > high and low[1] < low

// Inputs
rsiLength = input(10, "RSI Length")
rsiThreshold = input(76, "RSI Threshold")

// Preparing exit condition
// Calculating the RSI indicator based on the closing prices with the specified length.
rsiv = ta.rsi(close, rsiLength)

// Strategy logic
if (id)
    strategy.entry("Long", strategy.long)

if (rsiv > rsiThreshold)
    strategy.close("Long")

// Plotting
plot(rsiv, "RSI", color=color.blue)
hline(rsiThreshold, "RSI Threshold", color=color.red)
