// Copyright (c) GreenScale. All rights reserved.
// Description: Based on https://www.investopedia.com/terms/b/bollingerbands.asp
// @version=5
strategy("Bollinger Bands Strategy | Long", overlay = true)

// Define input variables
bbPeriod = input(10, title="Bollinger Bands Period")
bbStdDev = input(2, title="Bollinger Bands Standard Deviation")
smaPeriod = input(200, title="Simple Moving Average Period")
stopLossPercentage = input(0.10, title="Stop Loss Percentage")
takeProfitPercentage = input(0.40, title="Take Profit Percentage")

// Calculate the Bollinger Bands with the specified period and standard deviation
[middle, upper, lower] = ta.bb(close[1], bbPeriod, bbStdDev)

// Check for entry conditions: previous close below lower Bollinger Band and current close above the specified simple moving average period
if close[1] < lower and close > ta.sma(close, smaPeriod)
    strategy.entry("Long", strategy.long)

// Set stop loss and take profit levels based on percentages
SL = stopLossPercentage
TP = takeProfitPercentage

// Calculate stop loss and take profit prices for the long position
longstop = strategy.position_avg_price * (1 - SL)
longprofit = strategy.position_avg_price * (1 + TP)

// Exit the long position if position size is greater than 0, using the calculated stop loss and take profit prices
if strategy.position_size > 0
    strategy.exit(id="Exit", stop=longstop, limit=longprofit)
