// Copyright (c) GreenScale. All rights reserved.
// Description: Based on https://www.investopedia.com/terms/b/bollingerbands.asp
// @version=5
strategy("Daily | Long | Bollinger Bands Strategy", shorttitle="Bollinger Bands", overlay=true)

// Inputs
bbLength = input(10, "Bollinger Bands Length")
bbDeviation = input(2, "Bollinger Bands Deviation")
smaLength = input(160, "SMA Length")
stopLossPercentage = input(0.20, "Stop Loss Percentage")
takeProfitPercentage = input(0.8, "Take Profit Percentage")

// Calculating the Bollinger Bands with the specified length and standard deviation
[middle, upper, lower] = ta.bb(close[1], bbLength, bbDeviation)

// Checking if the previous close price was below the lower Bollinger Band and the current close price is above the specified SMA length
if close[1] < lower and close > ta.sma(close, smaLength)
    strategy.entry("Long", strategy.long)

// Calculating the stop loss and take profit prices for the long position based on percentages
longStop = strategy.position_avg_price * (1 - stopLossPercentage)
longProfit = strategy.position_avg_price * (1 + takeProfitPercentage)

// Exiting the long position if the position size is greater than 0, using the calculated stop loss and take profit prices
if strategy.position_size > 0
    strategy.exit(id="Exit", stop=longStop, limit=longProfit)
