// Copyright (c) GreenScale. All rights reserved.
// Description: Based on https://www.investopedia.com/terms/r/rsi.asp
// @version=5
strategy("RSI Strategy | Long", shorttitle="RSI Strategy", overlay=true)

// Setting the period for calculating the RSI
rsip = input(5, "RSI Period")

// Calculating the RSI based on the closing prices over the specified period
rsiv = ta.rsi(close, rsip)

// Checking if the RSI value is less than 30, the current closing price is higher than the 150-day SMA,
// and the current closing price is lower than the 30-day SMA
if rsiv < 30 and close > ta.sma(close, 150) and close < ta.sma(close, 30)
    strategy.entry("long", strategy.long)

// Setting the stop loss and take profit percentages
SL = input(0.10, "Stop Loss Percentage")
TP = input(0.60, "Take Profit Percentage")

// Calculating the stop loss and take profit levels based on the average position price
longStop = strategy.position_avg_price * (1 - SL)
longProfit = strategy.position_avg_price * (1 + TP)

// Checking if there is an open position
if strategy.position_size > 0
    strategy.exit("close", stop=longStop, limit=longProfit)
