// Copyright (c) GreenScale. All rights reserved.
// Description: Based on https://www.investopedia.com/terms/i/inside-days.asp
// @version=5
strategy("Daily | Long | Inside Day Strategy", shorttitle="Inside Day", overlay=true)

// Defining the inside day
id = high[1] > high and low[1] < low
// The inside day is defined as a condition where the previous day's high is greater than the current day's high
// and the previous day's low is lower than the current day's low.

// Inputs
rsiLength = input(10, "RSI Length")
rsiThreshold = input(76, "RSI Threshold")

// Preparing exit condition
rsiv = ta.rsi(close, rsiLength)
// Calculating the RSI indicator based on the closing prices with the specified length.

if id
    strategy.entry("Long", strategy.long)
    // Enter a long position if the inside day condition is true.

if rsiv > rsiThreshold
    strategy.close("Long")
    // Close the long position if the RSI value is above the specified threshold.
